global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: '5glabx-production'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 5s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 5s

  # API Backend metrics
  - job_name: 'api-backend'
    static_configs:
      - targets: ['api:3001']
    scrape_interval: 10s
    metrics_path: /metrics

  # Log Engine metrics
  - job_name: 'log-engine'
    static_configs:
      - targets: ['log-engine:3002']
    scrape_interval: 10s
    metrics_path: /metrics

  # Frontend metrics (if available)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s
    metrics_path: /metrics

  # Supabase metrics (external)
  - job_name: 'supabase'
    static_configs:
      - targets: ['api.supabase.com:443']
    scrape_interval: 60s
    metrics_path: /metrics
    scheme: https

  # Custom application metrics
  - job_name: '5glabx-app'
    static_configs:
      - targets: ['api:3001']
    scrape_interval: 15s
    metrics_path: /api/metrics
    params:
      format: ['prometheus']

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'api:3001'
        - 'log-engine:3002'
        - 'frontend:80'
    scrape_interval: 30s
    metrics_path: /health
    honor_labels: true